// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/CustomMessage.proto

package io.github.stefanosbou.kafka.custom.message;

public final class CustomMessage {
  private CustomMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userId = 1;
    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();

    // required string currencyFrom = 2;
    /**
     * <code>required string currencyFrom = 2;</code>
     */
    boolean hasCurrencyFrom();
    /**
     * <code>required string currencyFrom = 2;</code>
     */
    java.lang.String getCurrencyFrom();
    /**
     * <code>required string currencyFrom = 2;</code>
     */
    com.google.protobuf.ByteString
        getCurrencyFromBytes();

    // required string currencyTo = 3;
    /**
     * <code>required string currencyTo = 3;</code>
     */
    boolean hasCurrencyTo();
    /**
     * <code>required string currencyTo = 3;</code>
     */
    java.lang.String getCurrencyTo();
    /**
     * <code>required string currencyTo = 3;</code>
     */
    com.google.protobuf.ByteString
        getCurrencyToBytes();

    // required float amountSell = 4;
    /**
     * <code>required float amountSell = 4;</code>
     */
    boolean hasAmountSell();
    /**
     * <code>required float amountSell = 4;</code>
     */
    float getAmountSell();

    // required float amountBuy = 5;
    /**
     * <code>required float amountBuy = 5;</code>
     */
    boolean hasAmountBuy();
    /**
     * <code>required float amountBuy = 5;</code>
     */
    float getAmountBuy();

    // required float rate = 6;
    /**
     * <code>required float rate = 6;</code>
     */
    boolean hasRate();
    /**
     * <code>required float rate = 6;</code>
     */
    float getRate();

    // required string timePlaced = 7;
    /**
     * <code>required string timePlaced = 7;</code>
     */
    boolean hasTimePlaced();
    /**
     * <code>required string timePlaced = 7;</code>
     */
    java.lang.String getTimePlaced();
    /**
     * <code>required string timePlaced = 7;</code>
     */
    com.google.protobuf.ByteString
        getTimePlacedBytes();

    // required string originatingCountry = 8;
    /**
     * <code>required string originatingCountry = 8;</code>
     */
    boolean hasOriginatingCountry();
    /**
     * <code>required string originatingCountry = 8;</code>
     */
    java.lang.String getOriginatingCountry();
    /**
     * <code>required string originatingCountry = 8;</code>
     */
    com.google.protobuf.ByteString
        getOriginatingCountryBytes();
  }
  /**
   * Protobuf type {@code orders.Order}
   */
  public static final class Order extends
      com.google.protobuf.GeneratedMessage
      implements OrderOrBuilder {
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Order(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Order defaultInstance;
    public static Order getDefaultInstance() {
      return defaultInstance;
    }

    public Order getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              currencyFrom_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              currencyTo_ = input.readBytes();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              amountSell_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              amountBuy_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              rate_ = input.readFloat();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              timePlaced_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              originatingCountry_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.stefanosbou.kafka.custom.message.CustomMessage.internal_static_orders_Order_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.stefanosbou.kafka.custom.message.CustomMessage.internal_static_orders_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.stefanosbou.kafka.custom.message.CustomMessage.Order.class, io.github.stefanosbou.kafka.custom.message.CustomMessage.Order.Builder.class);
    }

    public static com.google.protobuf.Parser<Order> PARSER =
        new com.google.protobuf.AbstractParser<Order>() {
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Order(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // required string currencyFrom = 2;
    public static final int CURRENCYFROM_FIELD_NUMBER = 2;
    private java.lang.Object currencyFrom_;
    /**
     * <code>required string currencyFrom = 2;</code>
     */
    public boolean hasCurrencyFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string currencyFrom = 2;</code>
     */
    public java.lang.String getCurrencyFrom() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          currencyFrom_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string currencyFrom = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyFromBytes() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string currencyTo = 3;
    public static final int CURRENCYTO_FIELD_NUMBER = 3;
    private java.lang.Object currencyTo_;
    /**
     * <code>required string currencyTo = 3;</code>
     */
    public boolean hasCurrencyTo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string currencyTo = 3;</code>
     */
    public java.lang.String getCurrencyTo() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          currencyTo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string currencyTo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyToBytes() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required float amountSell = 4;
    public static final int AMOUNTSELL_FIELD_NUMBER = 4;
    private float amountSell_;
    /**
     * <code>required float amountSell = 4;</code>
     */
    public boolean hasAmountSell() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float amountSell = 4;</code>
     */
    public float getAmountSell() {
      return amountSell_;
    }

    // required float amountBuy = 5;
    public static final int AMOUNTBUY_FIELD_NUMBER = 5;
    private float amountBuy_;
    /**
     * <code>required float amountBuy = 5;</code>
     */
    public boolean hasAmountBuy() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required float amountBuy = 5;</code>
     */
    public float getAmountBuy() {
      return amountBuy_;
    }

    // required float rate = 6;
    public static final int RATE_FIELD_NUMBER = 6;
    private float rate_;
    /**
     * <code>required float rate = 6;</code>
     */
    public boolean hasRate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required float rate = 6;</code>
     */
    public float getRate() {
      return rate_;
    }

    // required string timePlaced = 7;
    public static final int TIMEPLACED_FIELD_NUMBER = 7;
    private java.lang.Object timePlaced_;
    /**
     * <code>required string timePlaced = 7;</code>
     */
    public boolean hasTimePlaced() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string timePlaced = 7;</code>
     */
    public java.lang.String getTimePlaced() {
      java.lang.Object ref = timePlaced_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timePlaced_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timePlaced = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTimePlacedBytes() {
      java.lang.Object ref = timePlaced_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timePlaced_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string originatingCountry = 8;
    public static final int ORIGINATINGCOUNTRY_FIELD_NUMBER = 8;
    private java.lang.Object originatingCountry_;
    /**
     * <code>required string originatingCountry = 8;</code>
     */
    public boolean hasOriginatingCountry() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string originatingCountry = 8;</code>
     */
    public java.lang.String getOriginatingCountry() {
      java.lang.Object ref = originatingCountry_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          originatingCountry_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string originatingCountry = 8;</code>
     */
    public com.google.protobuf.ByteString
        getOriginatingCountryBytes() {
      java.lang.Object ref = originatingCountry_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originatingCountry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userId_ = 0;
      currencyFrom_ = "";
      currencyTo_ = "";
      amountSell_ = 0F;
      amountBuy_ = 0F;
      rate_ = 0F;
      timePlaced_ = "";
      originatingCountry_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrencyFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrencyTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmountSell()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmountBuy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimePlaced()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOriginatingCountry()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCurrencyFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCurrencyToBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, amountSell_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, amountBuy_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, rate_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTimePlacedBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getOriginatingCountryBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCurrencyFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCurrencyToBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, amountSell_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, amountBuy_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, rate_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTimePlacedBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getOriginatingCountryBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.github.stefanosbou.kafka.custom.message.CustomMessage.Order prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code orders.Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.github.stefanosbou.kafka.custom.message.CustomMessage.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.stefanosbou.kafka.custom.message.CustomMessage.internal_static_orders_Order_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.stefanosbou.kafka.custom.message.CustomMessage.internal_static_orders_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.stefanosbou.kafka.custom.message.CustomMessage.Order.class, io.github.stefanosbou.kafka.custom.message.CustomMessage.Order.Builder.class);
      }

      // Construct using io.github.stefanosbou.kafka.custom.message.CustomMessage.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        currencyFrom_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        currencyTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        amountSell_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        amountBuy_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        rate_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        timePlaced_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        originatingCountry_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.stefanosbou.kafka.custom.message.CustomMessage.internal_static_orders_Order_descriptor;
      }

      public io.github.stefanosbou.kafka.custom.message.CustomMessage.Order getDefaultInstanceForType() {
        return io.github.stefanosbou.kafka.custom.message.CustomMessage.Order.getDefaultInstance();
      }

      public io.github.stefanosbou.kafka.custom.message.CustomMessage.Order build() {
        io.github.stefanosbou.kafka.custom.message.CustomMessage.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.github.stefanosbou.kafka.custom.message.CustomMessage.Order buildPartial() {
        io.github.stefanosbou.kafka.custom.message.CustomMessage.Order result = new io.github.stefanosbou.kafka.custom.message.CustomMessage.Order(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currencyFrom_ = currencyFrom_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.currencyTo_ = currencyTo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.amountSell_ = amountSell_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.amountBuy_ = amountBuy_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.rate_ = rate_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.timePlaced_ = timePlaced_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.originatingCountry_ = originatingCountry_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.stefanosbou.kafka.custom.message.CustomMessage.Order) {
          return mergeFrom((io.github.stefanosbou.kafka.custom.message.CustomMessage.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.stefanosbou.kafka.custom.message.CustomMessage.Order other) {
        if (other == io.github.stefanosbou.kafka.custom.message.CustomMessage.Order.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasCurrencyFrom()) {
          bitField0_ |= 0x00000002;
          currencyFrom_ = other.currencyFrom_;
          onChanged();
        }
        if (other.hasCurrencyTo()) {
          bitField0_ |= 0x00000004;
          currencyTo_ = other.currencyTo_;
          onChanged();
        }
        if (other.hasAmountSell()) {
          setAmountSell(other.getAmountSell());
        }
        if (other.hasAmountBuy()) {
          setAmountBuy(other.getAmountBuy());
        }
        if (other.hasRate()) {
          setRate(other.getRate());
        }
        if (other.hasTimePlaced()) {
          bitField0_ |= 0x00000040;
          timePlaced_ = other.timePlaced_;
          onChanged();
        }
        if (other.hasOriginatingCountry()) {
          bitField0_ |= 0x00000080;
          originatingCountry_ = other.originatingCountry_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasCurrencyFrom()) {
          
          return false;
        }
        if (!hasCurrencyTo()) {
          
          return false;
        }
        if (!hasAmountSell()) {
          
          return false;
        }
        if (!hasAmountBuy()) {
          
          return false;
        }
        if (!hasRate()) {
          
          return false;
        }
        if (!hasTimePlaced()) {
          
          return false;
        }
        if (!hasOriginatingCountry()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.stefanosbou.kafka.custom.message.CustomMessage.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.stefanosbou.kafka.custom.message.CustomMessage.Order) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userId = 1;
      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // required string currencyFrom = 2;
      private java.lang.Object currencyFrom_ = "";
      /**
       * <code>required string currencyFrom = 2;</code>
       */
      public boolean hasCurrencyFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string currencyFrom = 2;</code>
       */
      public java.lang.String getCurrencyFrom() {
        java.lang.Object ref = currencyFrom_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          currencyFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string currencyFrom = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencyFromBytes() {
        java.lang.Object ref = currencyFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string currencyFrom = 2;</code>
       */
      public Builder setCurrencyFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        currencyFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string currencyFrom = 2;</code>
       */
      public Builder clearCurrencyFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currencyFrom_ = getDefaultInstance().getCurrencyFrom();
        onChanged();
        return this;
      }
      /**
       * <code>required string currencyFrom = 2;</code>
       */
      public Builder setCurrencyFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        currencyFrom_ = value;
        onChanged();
        return this;
      }

      // required string currencyTo = 3;
      private java.lang.Object currencyTo_ = "";
      /**
       * <code>required string currencyTo = 3;</code>
       */
      public boolean hasCurrencyTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string currencyTo = 3;</code>
       */
      public java.lang.String getCurrencyTo() {
        java.lang.Object ref = currencyTo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          currencyTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string currencyTo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencyToBytes() {
        java.lang.Object ref = currencyTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string currencyTo = 3;</code>
       */
      public Builder setCurrencyTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        currencyTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string currencyTo = 3;</code>
       */
      public Builder clearCurrencyTo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currencyTo_ = getDefaultInstance().getCurrencyTo();
        onChanged();
        return this;
      }
      /**
       * <code>required string currencyTo = 3;</code>
       */
      public Builder setCurrencyToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        currencyTo_ = value;
        onChanged();
        return this;
      }

      // required float amountSell = 4;
      private float amountSell_ ;
      /**
       * <code>required float amountSell = 4;</code>
       */
      public boolean hasAmountSell() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float amountSell = 4;</code>
       */
      public float getAmountSell() {
        return amountSell_;
      }
      /**
       * <code>required float amountSell = 4;</code>
       */
      public Builder setAmountSell(float value) {
        bitField0_ |= 0x00000008;
        amountSell_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float amountSell = 4;</code>
       */
      public Builder clearAmountSell() {
        bitField0_ = (bitField0_ & ~0x00000008);
        amountSell_ = 0F;
        onChanged();
        return this;
      }

      // required float amountBuy = 5;
      private float amountBuy_ ;
      /**
       * <code>required float amountBuy = 5;</code>
       */
      public boolean hasAmountBuy() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float amountBuy = 5;</code>
       */
      public float getAmountBuy() {
        return amountBuy_;
      }
      /**
       * <code>required float amountBuy = 5;</code>
       */
      public Builder setAmountBuy(float value) {
        bitField0_ |= 0x00000010;
        amountBuy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float amountBuy = 5;</code>
       */
      public Builder clearAmountBuy() {
        bitField0_ = (bitField0_ & ~0x00000010);
        amountBuy_ = 0F;
        onChanged();
        return this;
      }

      // required float rate = 6;
      private float rate_ ;
      /**
       * <code>required float rate = 6;</code>
       */
      public boolean hasRate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required float rate = 6;</code>
       */
      public float getRate() {
        return rate_;
      }
      /**
       * <code>required float rate = 6;</code>
       */
      public Builder setRate(float value) {
        bitField0_ |= 0x00000020;
        rate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float rate = 6;</code>
       */
      public Builder clearRate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        rate_ = 0F;
        onChanged();
        return this;
      }

      // required string timePlaced = 7;
      private java.lang.Object timePlaced_ = "";
      /**
       * <code>required string timePlaced = 7;</code>
       */
      public boolean hasTimePlaced() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string timePlaced = 7;</code>
       */
      public java.lang.String getTimePlaced() {
        java.lang.Object ref = timePlaced_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          timePlaced_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timePlaced = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTimePlacedBytes() {
        java.lang.Object ref = timePlaced_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timePlaced_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timePlaced = 7;</code>
       */
      public Builder setTimePlaced(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        timePlaced_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timePlaced = 7;</code>
       */
      public Builder clearTimePlaced() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timePlaced_ = getDefaultInstance().getTimePlaced();
        onChanged();
        return this;
      }
      /**
       * <code>required string timePlaced = 7;</code>
       */
      public Builder setTimePlacedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        timePlaced_ = value;
        onChanged();
        return this;
      }

      // required string originatingCountry = 8;
      private java.lang.Object originatingCountry_ = "";
      /**
       * <code>required string originatingCountry = 8;</code>
       */
      public boolean hasOriginatingCountry() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string originatingCountry = 8;</code>
       */
      public java.lang.String getOriginatingCountry() {
        java.lang.Object ref = originatingCountry_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          originatingCountry_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string originatingCountry = 8;</code>
       */
      public com.google.protobuf.ByteString
          getOriginatingCountryBytes() {
        java.lang.Object ref = originatingCountry_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          originatingCountry_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string originatingCountry = 8;</code>
       */
      public Builder setOriginatingCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        originatingCountry_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string originatingCountry = 8;</code>
       */
      public Builder clearOriginatingCountry() {
        bitField0_ = (bitField0_ & ~0x00000080);
        originatingCountry_ = getDefaultInstance().getOriginatingCountry();
        onChanged();
        return this;
      }
      /**
       * <code>required string originatingCountry = 8;</code>
       */
      public Builder setOriginatingCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        originatingCountry_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:orders.Order)
    }

    static {
      defaultInstance = new Order(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:orders.Order)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_Order_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_orders_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/CustomMessage.proto\022\006orders\"\246\001\n\005" +
      "Order\022\016\n\006userId\030\001 \002(\005\022\024\n\014currencyFrom\030\002 " +
      "\002(\t\022\022\n\ncurrencyTo\030\003 \002(\t\022\022\n\namountSell\030\004 " +
      "\002(\002\022\021\n\tamountBuy\030\005 \002(\002\022\014\n\004rate\030\006 \002(\002\022\022\n\n" +
      "timePlaced\030\007 \002(\t\022\032\n\022originatingCountry\030\010" +
      " \002(\tB=\n*io.github.stefanosbou.kafka.cust" +
      "om.messageB\rCustomMessageH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_orders_Order_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_orders_Order_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_orders_Order_descriptor,
              new java.lang.String[] { "UserId", "CurrencyFrom", "CurrencyTo", "AmountSell", "AmountBuy", "Rate", "TimePlaced", "OriginatingCountry", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
